package com.restaurantplanner.notification.domain;

public enum NotificationType {
    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    RESERVATION_NO_SHOW,
    RESERVATION_SEATED,
    RESERVATION_COMPLETED,
    RESERVATION_UPDATED,
    RESERVATION_ASSIGNED,
    RESERVATION_REMINDER,
    SYSTEM
}
